"""add agent fields to invoices

Revision ID: 61db465aa427
Revises: 09c89f065a39
Create Date: 2026-01-09 11:16:32.443728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61db465aa427'
down_revision: Union[str, None] = '09c89f065a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('invoice_type', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('language', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('invoices', sa.Column('compliance_status', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('agent_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'agent_results')
    op.drop_column('invoices', 'compliance_status')
    op.drop_column('invoices', 'risk_flags')
    op.drop_column('invoices', 'risk_score')
    op.drop_column('invoices', 'language')
    op.drop_column('invoices', 'invoice_type')
    # ### end Alembic commands ###
